//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsWctToDb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Biodata", Namespace="http://schemas.datacontract.org/2004/07/WcfToDb")]
    [System.SerializableAttribute()]
    public partial class Biodata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UmurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nama {
            get {
                return this.NamaField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaField, value) != true)) {
                    this.NamaField = value;
                    this.RaisePropertyChanged("Nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Umur {
            get {
                return this.UmurField;
            }
            set {
                if ((this.UmurField.Equals(value) != true)) {
                    this.UmurField = value;
                    this.RaisePropertyChanged("Umur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahBiodata", ReplyAction="http://tempuri.org/IService1/TambahBiodataResponse")]
        int TambahBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahBiodata", ReplyAction="http://tempuri.org/IService1/TambahBiodataResponse")]
        System.Threading.Tasks.Task<int> TambahBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditBiodata", ReplyAction="http://tempuri.org/IService1/EditBiodataResponse")]
        int EditBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditBiodata", ReplyAction="http://tempuri.org/IService1/EditBiodataResponse")]
        System.Threading.Tasks.Task<int> EditBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HapusBiodata", ReplyAction="http://tempuri.org/IService1/HapusBiodataResponse")]
        int HapusBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HapusBiodata", ReplyAction="http://tempuri.org/IService1/HapusBiodataResponse")]
        System.Threading.Tasks.Task<int> HapusBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBiodata", ReplyAction="http://tempuri.org/IService1/GetBiodataResponse")]
        WindowsFormsWctToDb.ServiceReference1.Biodata GetBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBiodata", ReplyAction="http://tempuri.org/IService1/GetBiodataResponse")]
        System.Threading.Tasks.Task<WindowsFormsWctToDb.ServiceReference1.Biodata> GetBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBiodata", ReplyAction="http://tempuri.org/IService1/GetAllBiodataResponse")]
        WindowsFormsWctToDb.ServiceReference1.Biodata[] GetAllBiodata();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBiodata", ReplyAction="http://tempuri.org/IService1/GetAllBiodataResponse")]
        System.Threading.Tasks.Task<WindowsFormsWctToDb.ServiceReference1.Biodata[]> GetAllBiodataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsWctToDb.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsWctToDb.ServiceReference1.IService1>, WindowsFormsWctToDb.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int TambahBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.TambahBiodata(p);
        }
        
        public System.Threading.Tasks.Task<int> TambahBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.TambahBiodataAsync(p);
        }
        
        public int EditBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.EditBiodata(p);
        }
        
        public System.Threading.Tasks.Task<int> EditBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.EditBiodataAsync(p);
        }
        
        public int HapusBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.HapusBiodata(p);
        }
        
        public System.Threading.Tasks.Task<int> HapusBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.HapusBiodataAsync(p);
        }
        
        public WindowsFormsWctToDb.ServiceReference1.Biodata GetBiodata(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.GetBiodata(p);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWctToDb.ServiceReference1.Biodata> GetBiodataAsync(WindowsFormsWctToDb.ServiceReference1.Biodata p) {
            return base.Channel.GetBiodataAsync(p);
        }
        
        public WindowsFormsWctToDb.ServiceReference1.Biodata[] GetAllBiodata() {
            return base.Channel.GetAllBiodata();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWctToDb.ServiceReference1.Biodata[]> GetAllBiodataAsync() {
            return base.Channel.GetAllBiodataAsync();
        }
    }
}
